import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { createRequire } from 'node:module';
import test from 'node:test';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { isCliEntry } from '../src/entry-semantics.mjs';

// The four entry cases the predicate must decide, and the observable inert-load invariants.
// A regenerated dist/broker-bridge.cjs is the artifact under test — never source.
const BUNDLE_REL = '../dist/broker-bridge.cjs';        // regenerated by `npm run bundle` in bar 2
const EXPECTED_EXPORTS = ['LOGIN_REQUIRED', 'MAX_DISCOVERY_BYTES'];
const USAGE_EXIT_CODE = 2;                              // matches packaged.test.mjs:46
const USAGE_PATTERN = /Usage:/;                         // matches packaged.test.mjs:46
// entry-semantics predicate truth table (unit-level, no process spawn):
// isCliEntry(env) === true  iff the module IS the process entry
//   A) CJS require of a library:  { require: {main: <otherModule>}, module: <thisModule> } -> false
//   B) CJS process entry:         { require: {main: <thisModule>},  module: <thisModule> } -> true
//   C) ESM import as a library:   { metaUrl: 'file:///pkg/lib.mjs', argvHref: 'file:///pkg/cli.mjs' } -> false
//   D) ESM run as entry:          { metaUrl: 'file:///pkg/cli.mjs', argvHref: 'file:///pkg/cli.mjs' } -> true

const bundleAbsPath = fileURLToPath(new URL(BUNDLE_REL, import.meta.url));

test('cjs bundle require is inert', () => {
  const requireBundle = createRequire(import.meta.url);
  const originalArgv1 = process.argv[1];
  const originalExit = process.exit;
  process.argv[1] = fileURLToPath(pathToFileURL('/not-the-broker-bridge-entry.mjs'));
  process.exit = () => { throw new Error('main ran'); };
  try {
    const bundle = requireBundle(bundleAbsPath);
    for (const name of EXPECTED_EXPORTS) assert.ok(name in bundle, `${name} is exported`);
    assert.equal(typeof bundle.LOGIN_REQUIRED, 'string');
    assert.ok(bundle.LOGIN_REQUIRED.length > 0);
    assert.equal(typeof bundle.MAX_DISCOVERY_BYTES, 'number');
    assert.ok(Number.isInteger(bundle.MAX_DISCOVERY_BYTES));
    assert.ok(bundle.MAX_DISCOVERY_BYTES > 0);
  } finally {
    process.argv[1] = originalArgv1;
    process.exit = originalExit;
  }
});

test('cli entry invokes main', () => {
  const result = spawnSync(process.execPath, [bundleAbsPath], { encoding: 'utf8' });
  assert.equal(result.status, USAGE_EXIT_CODE);
  assert.match(result.stderr, USAGE_PATTERN);
});

test('entry predicate decides all four cases', () => {
  const thisModule = {};
  assert.equal(isCliEntry({ require: { main: {} }, module: thisModule }), false);
  assert.equal(isCliEntry({ require: { main: thisModule }, module: thisModule }), true);
  assert.equal(isCliEntry({ metaUrl: 'file:///pkg/lib.mjs', argvHref: 'file:///pkg/cli.mjs' }), false);
  assert.equal(isCliEntry({ metaUrl: 'file:///pkg/cli.mjs', argvHref: 'file:///pkg/cli.mjs' }), true);
});
