'use strict';
const test = require('node:test'), assert = require('node:assert/strict'), { generateKeyPairSync } = require('node:crypto');
const { parseRegistrationPackage, signRegistrationPackage, verifyRegistrationPackage, inspectRegistrationPackage } = require('../src/registration-packages');
const { logicalPackageContent, signedFixture } = require('./registration-fixtures');
test('signed package round-trips and verifies', () => { const f = signedFixture(); assert.deepEqual(parseRegistrationPackage(f.raw), f.document); assert.deepEqual(verifyRegistrationPackage(f.raw), f.document); });
test('inspectable before import', () => { const r = inspectRegistrationPackage(signedFixture().raw); assert.equal(r.signatureState, 'valid'); assert.equal(r.lines.length, 8); ['id:','displayName:','discovery:','redirectUris:','resource:','claims:','assurance:','bootstrap:'].forEach((x) => assert.ok(r.lines.some((line) => line.startsWith(x)))); });
test('secret-like field is rejected with path-only error', () => { const samples = [['clientSecret','planted-one'], ['api_key','planted-two'], ['refreshToken','planted-three'], ['displayName','-----BEGIN PRIVATE KEY-----'], ['displayName','client_secret=planted'], ['displayName','Bearer abcdefghijklmnop'], ['displayName','eyJabcdefghijklmn.abcdef.']]; for (const [key, value] of samples) { const c = structuredClone(logicalPackageContent); c[key] = value; assert.throws(() => signRegistrationPackage(c, generateKeyPairSync('ed25519').privateKey), (e) => e.message.startsWith('registration package validation failed: ') && !e.message.includes(value)); } });
test('schema rejects invalid documents', () => { const f = signedFixture(); const edits = [(d) => d.extra = true, (d) => d.package.extra = true, (d) => d.package.discovery.extra = true, (d) => d.package.discovery.issuer = 'http://issuer.test', (d) => d.package.redirectUris = ['http://localhost/callback'], (d) => d.package.claims.roles = 'bad claim', (d) => d.package.assurance = { claim: 'acr' }]; for (const edit of edits) { const d = structuredClone(f.document); edit(d); assert.throws(() => parseRegistrationPackage(JSON.stringify(d))); } assert.throws(() => parseRegistrationPackage(' '.repeat(65537))); });
test('tampering and invalid key material fail closed', () => { const f = signedFixture(), c = structuredClone(f.document), s = structuredClone(f.document); c.package.displayName = 'Changed'; s.signature.value = s.signature.value.slice(0, -2) + 'AA'; assert.throws(() => verifyRegistrationPackage(JSON.stringify(c))); assert.throws(() => verifyRegistrationPackage(JSON.stringify(s))); assert.equal(inspectRegistrationPackage(JSON.stringify(c)).signatureState, 'invalid'); const wrong = generateKeyPairSync('ed25519').publicKey.export({ format: 'der', type: 'spki' }).toString('base64'); assert.throws(() => verifyRegistrationPackage(f.raw, { trustedPublicKeySpki: wrong }), /untrusted signing key/); assert.throws(() => signRegistrationPackage(logicalPackageContent, 'private')); });
