import assert from 'node:assert/strict';
import test from 'node:test';
import { Readable } from 'node:stream';
import { createHttpHandler, normalizeGrant } from '../server.mjs';
import { admin, MutableGrantRepository, makeAuditSink, makeLogger, makeProbe, makeWriter } from './admin-console-fixtures.mjs';

function harness({ allowed = true } = {}) { const repository = new MutableGrantRepository(); const writer = makeWriter(); const auditSink = makeAuditSink(repository); const logger = makeLogger(); const probe = makeProbe(repository); const handler = createHttpHandler({ requireAdmin: async () => allowed ? admin : null, repository, credentialWriter: writer, brokerProbe: probe, auditSink, logger }); return { repository, writer, auditSink, logger, probe, handler }; }
async function call(h, method, path, body) { const request = Readable.from(body === undefined ? [] : [JSON.stringify(body)]); request.method = method; request.url = path; const response = { status: 0, headers: {}, chunks: [], writeHead(status, headers) { this.status = status; this.headers = headers; }, end(chunk = '') { this.chunks.push(Buffer.from(chunk)); } }; await h.handler(request, response); return { status: response.status, body: JSON.parse(Buffer.concat(response.chunks).toString()) }; }

test('all routes demand a trusted administrator', async () => { const h = harness({ allowed: false }); for (const route of ['/api/identity-integrations', '/api/connections', '/api/connections/azure:orders/grants', '/api/connections/azure:orders/health', '/api/connections/azure:orders/usage', '/api/connections/azure:orders/audit']) assert.equal((await call(h, 'GET', route)).status, 403); assert.equal(h.repository.calls, 0); });
test('query before side effect is rejected including a bare query', async () => { for (const suffix of ['?', '?anything=1']) { const h = harness(); const before = h.repository.calls; const result = await call(h, 'POST', `/api/connections${suffix}`, { displayName: 'Orders', provider: 'reference', credential: 'distinctive-credential' }); assert.equal(result.status, 400); assert.equal(h.repository.calls, before); assert.equal(h.writer.writes.length, 0); assert.equal(h.auditSink.writes.length, 0); assert.equal(h.probe.calls, 0); assert.equal(h.logger.entries.length, 0); } });
test('write-only credential never crosses a public boundary', async () => { const h = harness(); const secret = 'distinctive-credential-value'; const created = await call(h, 'POST', '/api/connections', { displayName: 'Orders', provider: 'reference', credential: secret }); assert.equal(created.status, 201); assert.equal(h.writer.writes.length, 1); assert.equal(h.writer.writes[0].credential, secret); const later = await Promise.all([call(h, 'GET', '/api/connections'), call(h, 'GET', '/api/connections/azure:orders/audit')]); const visible = JSON.stringify([created, later, h.logger.entries, h.auditSink.writes]); for (const barred of [secret, 'Authorization', 'Bearer', 'client_secret', 'scope', 'https://vendor.example.test', 'secret-name']) assert.equal(visible.includes(barred), false); assert.deepEqual(Object.keys(created.body.connection).sort(), ['createdAt', 'displayName', 'id', 'provider', 'status']); });
test('identity handoffs, grants, and redacted audit follow the closed contract', async () => { const h = harness(); const identities = await call(h, 'GET', '/api/identity-integrations'); assert.deepEqual(identities.body.identityIntegrations.map(x => x.handoffKind).sort(), ['generic', 'marketplace', 'private']); for (const [kind, subject] of [['user', 'user:alice'], ['group', 'group:team'], ['workload', 'workload:billing']]) { const result = await call(h, 'POST', '/api/connections/azure:orders/grants', { kind, subject }); assert.equal(result.status, 201); assert.deepEqual(Object.keys(result.body.grant).sort(), ['connectionId', 'id', 'kind', 'subject']); }
  for (const bad of [['group', 'GROUP:ops'], ['group', 'group:Ops'], ['group', 'group:ops '], ['group', 'group:ops:extra'], ['unknown', 'unknown:ops'], ['group', 'claims=ops'], ['group', 'scope:all'], ['group', 'operation:write']]) assert.throws(() => normalizeGrant(...bad));
  assert.equal((await call(h, 'POST', '/api/connections/azure:orders/grants', { kind: 'group', subject: 'group:ops' })).status, 400);
  assert.equal((await call(h, 'POST', '/api/connections', { displayName: 'x', provider: 'y', secret: 'no' })).status, 400);
  const auditResult = await call(h, 'GET', '/api/connections/azure:orders/audit'); assert.ok(auditResult.body.audit.every(entry => Object.keys(entry).every(key => ['at', 'action', 'connectionId', 'outcome'].includes(key)))); assert.equal(JSON.stringify(auditResult.body).includes('credential'), false); // redacted audit excludes credentials
});
